### ISSUE TITLE
`fsharp/signature is not supported` when switching files

### ISSUE THREAD

**Issue by Jeaciaz** [ionide/Ionide-vim#57]
**Describe the bug**
After setting up the plugin, opening the first .fs file works fine, however opening a file in a deeper-nested folder using i.e. netrw throws the following error:
```
Error detected while processing function fsharp#OnCursorMove[2]..fsharp#showSignature[10]..<SNR>11_signature[1]..<SNR>11_call:
line    5:
method fsharp/signature is not supported by any of the servers registered for the current buffer
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Create template using https://safe-stack.github.io/docs/quickstart/
2. Inside template folder, do `nvim -u mini.vim ./Build.fs`
3. Do `:NTree`, navigate to src/Shared/Shared.fs, open it

**Expected behaviour**
It opens the selected file with no error and continues to work fine.

**Screenshots**

**Environment (please complete the following information):**
 - OS: masOS Catalina 10.15.7
 - Vim / Neovim version: Neovim v0.7.0
 - dotnet SDK version: 6.0.301
 - mono / .Net Framework version: -

**Additional context**
The mini.vim I used to reproduce the problem: 
```
call plug#begin()
Plug 'ionide/Ionide-vim' 
call plug#end()

nnoremap <C-f> :Ntree<CR>
```

**Comment by cannorin** [comment]
It looks like this is (also) the problem caused by the slow loading speed of FSAC.

Here, `./Build.fs` is a build script and `Shared,fs` is the actual project, so they belong in a different workspace. FSAC takes some time to load a new workspace, but Ionide-vim sends the `fsharp#showSignature` as soon as you open `Shared.fs`, which means FSAC is not ready yet to respond, resulting with the error.

This is caused by the signature-showing feature of Ionide-vim, which you can disable by `let g:fsharp#show_signature_on_cursor_move = 0`. I'm actually thinking this to be disabled by default since it's causing another problem in #58.

**Comment by cannorin** [comment]
This feature is now disabled by default.
